### PR TITLE
added additional step to avoid no directory errors;

### PR DESCRIPTION
**Pull request by aditya109**
Solves: #248 
Signed-off-by: Aditya Kumar <aditya@gravityilabs.com>

### CODE REVIEW

**Comment by patsevanton** [comment]
If script:
```

```
Output:
```
vagrant@master-1:~$ for instance in master-1 master-2; do
>   ssh ${instance} sudo mkdir -p /var/lib/kubernetes/  sudo mv encryption-config.yaml /var/lib/kubernetes/
> done

mkdir: cannot create directory ‘encryption-config.yaml’: File exists
mkdir: cannot create directory ‘encryption-config.yaml’: File exists

```

**Comment by patsevanton** [comment]
Work script:
```
for instance in master-1 master-2; do
  ssh ${instance} sudo mkdir -p /var/lib/kubernetes/
  ssh ${instance} sudo mv encryption-config.yaml /var/lib/kubernetes/
done
```

**Comment by patsevanton** [comment]
or
```
for instance in master-1 master-2; do
  ssh ${instance} sudo mkdir -p /var/lib/kubernetes; sudo mv ~/encryption-config.yaml /var/lib/kubernetes/
done
```

**Review by vsvistunou — CHANGES_REQUESTED** [review]
Hello! Both commands should be either quoted (like `ssh ${instance} 'sudo mkdir -p /var/lib/kubernetes; sudo mv ~/encryption-config.yaml /var/lib/kubernetes/'` ), or split into two `ssh ... `commands within the _for_ block. Otherwise, the second command will be executed locally, not on a remote node.

**Comment by fireflycons** [comment]
Hi @aditya109  @patsevanton  @vsvistunou 
We have now merged a major change to bring this to v1.24.
This has been addressed as part of the upgrade.

**Pull request closed without merging**
