### PR TITLE
Adjust markdown formatting

### PR DESCRIPTION
**Pull request by vazhnov**
Adjust markdown formatting:

* Remove extra capitalization.
* Remove extra curly braces \{\} inside Bash code blocks.
* Use in-line code block \`\` for IP-addresses, file names and commands.
* Add a dot at the end of sentences.
* Use Markdown list in `differences-to-original.md`. Also add escaping for angle brackets \<\>.
* No logic changes were made, only formatting improvements.

This is more like test to understand should I continue to improve formatting or should I stop trying :)
Also, if it is needed, I can split it to smaller changes.

### CODE REVIEW

**Comment by fireflycons** [comment]
I agree with some of this
* Remove extra capitalization - that's a point of personal preference. I think capitalized headers stand out better.
* Remove extra curly braces {} inside Bash code blocks - They are there for a reason. If you paste a block of code within braces, then it is not executed immediately by the shell - you have to press ENTER. Quite often when making changes to this repo and I have multiple terminals open, it gives me a chance to check that I have pasted the block into the correct terminal before it executes in the wrong terminal and borks everything.
* Use in-line code block `` for IP-addresses, file names and commands - This is fair. Probably places where I forgot to do it myself.
* Add a dot at the end of sentences - likewise.
* Use Markdown list in differences-to-original.md. Also add escaping for angle brackets <> - makes sense

**Comment by vazhnov** [comment]
* I think capitalization can be easily done automatically — for example, with custom CSS in web-browser settings, so person who prefer it, will see all headers capitalized everywhere, on all web-sites. Reverse process impossible to do automatically, because it is not always clear, for example, "The Kube Proxy client certificate". I'm trying to follow [Wikipedia:Naming conventions (capitalization)](https://en.wikipedia.org/wiki/Wikipedia:Naming_conventions_(capitalization)).
* curly braces `{}` inside Bash code blocks — sorry, I didn't think they were added by purpose. I thought they came from some other format by mistake. I can return them back.

**Comment by vazhnov** [comment]
Should I change something in the merge request?
I'm afraid after some time there may be conflicts with any other changes and it will be much harder to merge my changes.

**Comment by fireflycons** [comment]
To be fair, not a lot changes in here unless the lab gets a version update, which will be due fairly soon, including a section on how to do it on Apple Silicon. Currently there are no conflicts so feel free to make the changes I suggested to this PR.

**Comment by vazhnov** [comment]
So, I'm going to return back the curly braces `{}`.
Should I restore capitalized headers?
Anything else?

**Comment by fireflycons** [comment]
Yes, and yes. The header style is in line with our [other sites](https://github.com/kodekloudhub) so best leave that.
Minor errors like punctuation and failure to `code block` things - definitely.

**Comment by vazhnov** [comment]
Done!
Please check (and merge if everything is OK).

**Pull request merged**
